### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by Deduction42** [sylvaticus/OdsIO.jl#6] opened 2018-12-20 15:25 UTC
I have found, on two occasions, that reading data from spreadsheets increases memory, even when the output overwrites an identical previous result or when a small portion of the output is returned as an output to a julia function (which means a lot of memory should be cleared when the function exits). Simply using OpenOffice to convert the sheets to CSV files and using DelimitedFiles.jl solved the problem (I guess this is the preferred approach to performance-heavy code), but it may be worth looking into figuring out where this memory leak seems to be occurring. It may also be due to some formatting issues within the file (which I can't upload due to it having proprietary information) and could be an issue with the base Python package as well, so it if it not easily found, it is quite understandable.

**Comment by sylvaticus** [comment] 2018-12-20 15:33
Hello, can you try to reproduce it using an input file as simple as possible that still generate the memory leak ?

**Comment by sylvaticus** [comment] 2019-08-21 11:31
Closing, because as it stands today, the bug report is too generic. Feel free to reopen if you can add more details... (altought I also think that if there is a memory leak it is likely in the Python module)..

**Closed as completed by sylvaticus** 2019-08-21 11:31 UTC
